// <auto-generated />
using System;
using AirQuality.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirQuality.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319142750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirQuality.Server.Models.ActionType", b =>
                {
                    b.Property<int>("ActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("action_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionTypeId"));

                    b.HasKey("ActionTypeId");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AffiliateProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AffiliateUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("affiliate_url");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("MinAqiTrigger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("min_aqi_trigger");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("TargetHealthCondition")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("All")
                        .HasColumnName("target_health_condition");

                    b.HasKey("ProductId");

                    b.ToTable("AffiliateProducts");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AiModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Hyperparameters")
                        .HasColumnType("text")
                        .HasColumnName("hyperparameters");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("is_active");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("model_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("version");

                    b.HasKey("ModelId");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AirQualityObservation", b =>
                {
                    b.Property<int>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("observation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationId"));

                    b.Property<int?>("CalculatedAqi")
                        .HasColumnType("int")
                        .HasColumnName("calculated_aqi");

                    b.Property<double?>("Co")
                        .HasColumnType("float")
                        .HasColumnName("co");

                    b.Property<double?>("Humidity")
                        .HasColumnType("float")
                        .HasColumnName("humidity");

                    b.Property<int>("IsImputed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("is_imputed");

                    b.Property<int>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("is_valid");

                    b.Property<double?>("No2")
                        .HasColumnType("float")
                        .HasColumnName("no2");

                    b.Property<double?>("O3")
                        .HasColumnType("float")
                        .HasColumnName("o3");

                    b.Property<double?>("Pm10")
                        .HasColumnType("float")
                        .HasColumnName("pm10");

                    b.Property<double?>("Pm25")
                        .HasColumnType("float")
                        .HasColumnName("pm25");

                    b.Property<double?>("Pressure")
                        .HasColumnType("float")
                        .HasColumnName("pressure");

                    b.Property<double?>("So2")
                        .HasColumnType("float")
                        .HasColumnName("so2");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("float")
                        .HasColumnName("wind_speed");

                    b.HasKey("ObservationId");

                    b.HasIndex("StationId");

                    b.ToTable("AirQualityObservations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AlertConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("AqiThreshold")
                        .HasColumnType("int")
                        .HasColumnName("aqi_threshold");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("is_active");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ConfigId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("AlertConfigs");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AqiCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("color_code");

                    b.Property<string>("HealthRecommendation")
                        .HasColumnType("text")
                        .HasColumnName("health_recommendation");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("level_name");

                    b.Property<int>("MaxAqi")
                        .HasColumnType("int")
                        .HasColumnName("max_aqi");

                    b.Property<int>("MinAqi")
                        .HasColumnType("int")
                        .HasColumnName("min_aqi");

                    b.HasKey("CategoryId");

                    b.ToTable("AQICategories");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("action_type_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AirQuality.Server.Models.CommunityReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("ReportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("report_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("Upvotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("upvotes");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityReports");
                });

            modelBuilder.Entity("AirQuality.Server.Models.ForecastData", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forecast_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<string>("ConfidenceInterval")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("confidence_interval");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<int?>("PredictedAqi")
                        .HasColumnType("int")
                        .HasColumnName("predicted_aqi");

                    b.Property<double?>("PredictedPm25")
                        .HasColumnType("float")
                        .HasColumnName("predicted_pm25");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    b.Property<DateTime>("TargetTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("target_time");

                    b.HasKey("ForecastId");

                    b.HasIndex("ModelId");

                    b.HasIndex("StationId");

                    b.ToTable("ForecastData");
                });

            modelBuilder.Entity("AirQuality.Server.Models.ModelEvaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("evaluated_at");

                    b.Property<double?>("Mae")
                        .HasColumnType("float")
                        .HasColumnName("mae");

                    b.Property<double?>("Mape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0)
                        .HasColumnName("mape");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<double?>("R2Score")
                        .HasColumnType("float")
                        .HasColumnName("r2_score");

                    b.Property<double?>("Rmse")
                        .HasColumnType("float")
                        .HasColumnName("rmse");

                    b.HasKey("EvaluationId");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelEvaluations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.NotificationHistory", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationHistory");
                });

            modelBuilder.Entity("AirQuality.Server.Models.NotificationPlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("ApiConfig")
                        .HasColumnType("text")
                        .HasColumnName("api_config");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("platform_name");

                    b.HasKey("PlatformId");

                    b.ToTable("NotificationPlatforms");
                });

            modelBuilder.Entity("AirQuality.Server.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AirQuality.Server.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("station_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("HealCondition")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("heal_condition");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AirQuality.Server.Models.UserFavoriteStation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("station_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("added_at");

                    b.HasKey("UserId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("UserFavoriteStations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.UserLinkedAccount", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("link_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("external_account_id");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("linked_at");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LinkId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLinkedAccounts");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AirQualityObservation", b =>
                {
                    b.HasOne("AirQuality.Server.Models.Station", "Station")
                        .WithMany("AirQualityObservations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AlertConfig", b =>
                {
                    b.HasOne("AirQuality.Server.Models.NotificationPlatform", "NotificationPlatform")
                        .WithMany("AlertConfigs")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.Station", "Station")
                        .WithMany("AlertConfigs")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("AlertConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationPlatform");

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AuditLog", b =>
                {
                    b.HasOne("AirQuality.Server.Models.ActionType", "ActionType")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.CommunityReport", b =>
                {
                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("CommunityReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.ForecastData", b =>
                {
                    b.HasOne("AirQuality.Server.Models.AiModel", "AiModel")
                        .WithMany("ForecastData")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.Station", "Station")
                        .WithMany("ForecastData")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModel");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AirQuality.Server.Models.ModelEvaluation", b =>
                {
                    b.HasOne("AirQuality.Server.Models.AiModel", "AiModel")
                        .WithMany("ModelEvaluations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModel");
                });

            modelBuilder.Entity("AirQuality.Server.Models.NotificationHistory", b =>
                {
                    b.HasOne("AirQuality.Server.Models.NotificationPlatform", "NotificationPlatform")
                        .WithMany("NotificationHistories")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("NotificationHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationPlatform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.User", b =>
                {
                    b.HasOne("AirQuality.Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AirQuality.Server.Models.UserFavoriteStation", b =>
                {
                    b.HasOne("AirQuality.Server.Models.Station", "Station")
                        .WithMany("UserFavoriteStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("UserFavoriteStations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.UserLinkedAccount", b =>
                {
                    b.HasOne("AirQuality.Server.Models.NotificationPlatform", "NotificationPlatform")
                        .WithMany("UserLinkedAccounts")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirQuality.Server.Models.User", "User")
                        .WithMany("UserLinkedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationPlatform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirQuality.Server.Models.ActionType", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("AirQuality.Server.Models.AiModel", b =>
                {
                    b.Navigation("ForecastData");

                    b.Navigation("ModelEvaluations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.NotificationPlatform", b =>
                {
                    b.Navigation("AlertConfigs");

                    b.Navigation("NotificationHistories");

                    b.Navigation("UserLinkedAccounts");
                });

            modelBuilder.Entity("AirQuality.Server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AirQuality.Server.Models.Station", b =>
                {
                    b.Navigation("AirQualityObservations");

                    b.Navigation("AlertConfigs");

                    b.Navigation("ForecastData");

                    b.Navigation("UserFavoriteStations");
                });

            modelBuilder.Entity("AirQuality.Server.Models.User", b =>
                {
                    b.Navigation("AlertConfigs");

                    b.Navigation("AuditLogs");

                    b.Navigation("CommunityReports");

                    b.Navigation("NotificationHistories");

                    b.Navigation("UserFavoriteStations");

                    b.Navigation("UserLinkedAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
